"""Initial PROMED v2 schema with Tablet model

Revision ID: 494fd4a4c1b6
Revises: 
Create Date: 2025-08-12 17:19:34.989243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494fd4a4c1b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DATE(), nullable=False))

    op.drop_table('tablet')
    # ### end Alembic commands ###
