"""Initial migration

Revision ID: fd14c053a979
Revises: 7375cc089ae2
Create Date: 2025-08-16 17:05:45.551812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd14c053a979'
down_revision = '7375cc089ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
